apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops-container
          image: veerase/devops-app:e103c69bb14bbc95d2f7c4a77929c6d5ff5c42f8
          ports:
            - containerPort: 3000
