name: DevOps CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t veerase/devops-app:${{ github.sha }} -f docker/Dockerfile .

      - name: Push Image
        run: docker push veerase/devops-app:${{ github.sha }}

      - name: Update Deployment Manifest
        run: |
          sed -i "s|image:.*|image: veerase/devops-app:${{ github.sha }}|g" kubernetes/deployment.yaml

      - name: Commit Updated Manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update image tag"
          git push
